[package]
name = "project-manager"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "actions",

  "tests"
]

[dependencies]
actions = { path = "actions" }
octocrab = "0.17.0"
tokio = { version = "1", features = ["full"] }
