[package]
name = "actions"
version = "0.1.0"
edition = "2021"

[lib]
name = "actions"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
octocrab = "0.17.0"
